import json
import os

from gradio_client import Client


SPACE_ID = "orhanaydinn/oax-humanoid-agent-api"

HF_TOKEN = os.getenv("HF_TOKEN")


class HuggingFaceAgent:
    """
    Hosted Hugging Face Space agent.

    This agent does not download the model locally.
    It sends the current observation to a hosted Hugging Face Space API and
    receives a JSON tool call generated by the OAX-1B-Humanoid model.
    """

    def __init__(self, verbose=False):
        self.verbose = verbose

        print("[HuggingFaceAgent] Using hosted Hugging Face Space API.", flush=True)
        print(f"[HuggingFaceAgent] Space: {SPACE_ID}", flush=True)

        if HF_TOKEN:
            self.client = Client(SPACE_ID, hf_token=HF_TOKEN)
        else:
            self.client = Client(SPACE_ID)

    def act(self, observation, max_new_tokens=180):
        observation_json = json.dumps(observation, ensure_ascii=False)

        try:
            result = self.client.predict(
                observation_json,
                max_new_tokens,
                api_name="/generate_action",
            )

            if self.verbose:
                print("\n[HuggingFaceAgent] Hosted raw response:", flush=True)
                print(result, flush=True)

            if isinstance(result, str):
                action = json.loads(result)
            elif isinstance(result, dict):
                action = result
            else:
                action = None

            if action is None:
                return self.build_fallback_action("Hosted API returned invalid output.")

            return self.normalise_action(action)

        except Exception as exc:
            print("[HuggingFaceAgent ERROR]", str(exc), flush=True)
            return self.build_fallback_action(str(exc))

    def normalise_action(self, action):
        if not isinstance(action, dict):
            return self.build_fallback_action(str(action))

        allowed_types = {"chat", "tool_call", "clarify", "refuse"}

        if action.get("type") not in allowed_types:
            action["type"] = "tool_call"

        if "response" not in action:
            action["response"] = ""

        if "tool" not in action:
            action["tool"] = None

        if "arguments" not in action or action["arguments"] is None:
            action["arguments"] = {}

        if not isinstance(action["arguments"], dict):
            action["arguments"] = {}

        return action

    def build_fallback_action(self, raw_output=""):
        return {
            "type": "tool_call",
            "response": "Fallback action selected because hosted model output was unavailable or invalid.",
            "tool": "get_robot_status",
            "arguments": {
                "raw_output": raw_output[:300] if raw_output else "",
            },
        }